### ISSUE TITLE
Document build instructions

### ISSUE THREAD

**Issue by chrisoldwood** [pbthorste/avtool#3]
I'm a Go newbie so am not sure what the simplest instructions are for building this tool but after some fumbling around I narrowed it down to the following on Windows:

```
> go get gopkg.in/urfave/cli.v1
> go get github.com/pbthorste/avtool
> pushd %GOPATH%\src\github.com\pbthorste\avtool\cmd\avtool
> go build
```

It would be nice to have some simple build instructions in the `README` for those people like myself that just need to build Go based tools so they can run them.

**Comment by pbthorste** [comment]
Hi, I added a makefile and updated the readme, hope that is enough.

**Comment by chrisoldwood** [comment]
Sadly a makefile doesn't work on Windows out of the box and even with GoW (Gnu on Windows) installed, which provides a Windows build of `make`, you get:
```
> make
go get -u -v "github.com/mitchellh/gox"
github.com/mitchellh/gox (download)
github.com/mitchellh/iochan (download)
github.com/mitchellh/iochan
github.com/mitchellh/gox
The syntax of the command is incorrect.
make: *** [build] Error 1
```

The bit that initially catches me out is doing a `go get` instead of `git clone` and needing to fetch the dependent packages, hence I listed my manual steps when doing this from scratch. Personally I would have been perfectly happy with a few manual steps listed in the README as it's generally easy to run one-line statements in a Windows shell however the makefile still adds another source of documentation which is jolly useful.

Either way, many thanks for even bothering to listen and providing any instructions!

**Comment by chrisoldwood** [comment]
As an aside for anyone waiting to build this on Windows and make the `avtool.exe --version` verb work correctly you need to bind the version number at build time by adapting the steps from the `makefile`:
```
> for /f %i in ('git describe --tags --always') do @set VERSION=%i
> go build -ldflags "-X main.version=%VERSION%"
```
